# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51f34a645d67b0682b8efc9173927eede7f835be86c08fdd214244267dbda18d7b3e7af9cb0788e7178647cd8cc77ac0dde61bbe0521e3b5d33078f00c79b38b

test:
  secret_key_base: 0c936eca771535340bf59a88fc36380ad799c8e4318a05dbabe7a604824a3141016ee4c874d3106a361ec9e8d316b71a742074f19841b5376282e3eed597d17c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
